version: '3'
services:
    ###
    # Databases of various kind
    # PostgreSQL databse
    postgres:
        image: postgres
        restart: always
        volumes:
            - ./data/postgresql/data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: wonderland
            POSTGRES_PASSWORD: wonderlandsecret
            POSTGRES_DB: wonderland

    adminer:
        image: adminer
        depends_on:
            - postgres
        ports:
            - 8080:8080
        restart: always

    # Mongo DB
    mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: wonderland
            MONGO_INITDB_ROOT_PASSWORD: wonderlandsecret

    mongo_express:
        image: mongo-express
        restart: always
        depends_on:
            - mongo
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: wonderland
            ME_CONFIG_MONGODB_ADMINPASSWORD: wonderlandsecret
            ME_CONFIG_MONGODB_URL: mongodb://wonderland:wonderlandsecret@mongo:27017/

    redis:
        image: redis/redis-stack:latest
        restart: always
        ports:
            - 6379:6379
            - 8001:8001
        environment:
            REDIS_ARGS: '--requirepass wonderlandsecret'
