version: "3.1"

services:
    ###
    # Databases of various kind
    # PostgreSQL databse
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: wonderland
            POSTGRES_PASSWORD: wondersecret
            POSTGRES_DB: wonderland

    adminer:
        image: adminer
        restart: always

    # Mongo DB
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: wonderland
            MONGO_INITDB_ROOT_PASSWORD: wondersecret

    mongo_express:
        image: mongo-express
        restart: always
        depends_on:
            - mongo
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: wonderland
            ME_CONFIG_MONGODB_ADMINPASSWORD: wondersecret
            ME_CONFIG_MONGODB_URL: mongodb://wonderland:wondersecret@mongo:27017/
